site_name: pinchsearcher
site_description: A social media content searcher that filters content when you pinch in/out from a topic modeling graph
site_author: William Bonvini

repo_url: https://github.com/WilliamBonvini/sydraw
edit_uri: https://github.com/WilliamBonvini/sydraw/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Usage:
    - Terminology: usage/terminology.md
    - Points Generation: usage/point_generation.md
    - Parametric Models: usage/parametric_models.md
    - Output Folder Structure: usage/output_folder_structure.md
  - About:
      - Release Notes: about/changelog.md
      - Contributor Guide: about/contributing.md
      - License: about/license.md

